-- Tabla para almacenar las conversaciones de ElevenLabs
CREATE TABLE public.elevenlabs_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  
  -- Identificadores principales
  conversation_id TEXT NOT NULL UNIQUE,
  agent_id TEXT NOT NULL,
  status TEXT,
  workspace_id BIGINT,
  
  -- Metadata
  call_duration_secs INTEGER,
  cost DECIMAL(10, 4),
  
  -- Charging
  dev_discount DECIMAL(10, 4),
  is_burst BOOLEAN,
  llm_usage DECIMAL(10, 4),
  llm_price DECIMAL(10, 4),
  llm_charge DECIMAL(10, 4),
  call_charge DECIMAL(10, 4),
  free_minutes_consumed DECIMAL(10, 4),
  free_llm_dollars_consumed DECIMAL(10, 4),
  
  -- Phone Call
  phone_number_id TEXT,
  agent_number TEXT,
  external_number TEXT,
  call_type TEXT,
  call_sid TEXT,
  
  -- Batch Call
  batch_call_id TEXT,
  batch_call_recipient_id TEXT,
  
  -- Datos completos (raw)
  raw_data JSONB,
  
  -- Timestamps
  conversation_date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  
  CONSTRAINT elevenlabs_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT elevenlabs_conversations_workspace_id_fkey FOREIGN KEY (workspace_id) 
    REFERENCES public.workspaces(id) ON DELETE SET NULL
);

-- Índices para mejorar el rendimiento
CREATE INDEX idx_elevenlabs_conversations_conversation_id ON public.elevenlabs_conversations(conversation_id);
CREATE INDEX idx_elevenlabs_conversations_workspace_id ON public.elevenlabs_conversations(workspace_id);
CREATE INDEX idx_elevenlabs_conversations_agent_number ON public.elevenlabs_conversations(agent_number);
CREATE INDEX idx_elevenlabs_conversations_date ON public.elevenlabs_conversations(conversation_date);
CREATE INDEX idx_elevenlabs_conversations_call_sid ON public.elevenlabs_conversations(call_sid);

-- Row Level Security
ALTER TABLE public.elevenlabs_conversations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.elevenlabs_conversations 
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.elevenlabs_conversations 
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users only" ON public.elevenlabs_conversations 
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users only" ON public.elevenlabs_conversations 
  FOR DELETE USING (auth.role() = 'authenticated');

-- Comentarios
COMMENT ON TABLE public.elevenlabs_conversations IS 'Almacena todas las conversaciones de ElevenLabs con detalles de costos y llamadas';
COMMENT ON COLUMN public.elevenlabs_conversations.agent_number IS 'Número del agente (FROM) - usado para asociar con workspace';
